//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Settings/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/GameInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""Janken"",
            ""id"": ""29578dc3-6963-4303-b106-a7b89ec733ef"",
            ""actions"": [
                {
                    ""name"": ""LeftUpRock"",
                    ""type"": ""Button"",
                    ""id"": ""d61b2fea-e352-401f-aec7-a005c896c538"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftUpScissors"",
                    ""type"": ""Button"",
                    ""id"": ""49affd24-9faf-4515-b1a0-ee879801d305"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftUpPaper"",
                    ""type"": ""Button"",
                    ""id"": ""6b0bf0b5-12c7-45b2-b2d8-3360bc541459"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDownRock"",
                    ""type"": ""Button"",
                    ""id"": ""8d25b24d-7e98-4096-84d0-97fee8803d8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDownScissors"",
                    ""type"": ""Button"",
                    ""id"": ""4c261c6f-69e9-4789-9b7f-7e6a6ab86d0e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDownPaper"",
                    ""type"": ""Button"",
                    ""id"": ""0e36e019-3509-4c6e-a254-6072add8a958"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightUpRock"",
                    ""type"": ""Button"",
                    ""id"": ""d8629559-0fec-43fa-8349-ea14e6dc7dc0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightUpScissors"",
                    ""type"": ""Button"",
                    ""id"": ""039c624b-ded2-487a-b232-e71e5d6efa9c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightUpPaper"",
                    ""type"": ""Button"",
                    ""id"": ""3abff164-01e6-458d-833f-757211c906b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDownRock"",
                    ""type"": ""Button"",
                    ""id"": ""89f77df0-81aa-49f5-aa12-f71745a9275c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDownScissors"",
                    ""type"": ""Button"",
                    ""id"": ""8b42bec8-0796-42ca-81bf-6be30d34b2eb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDownPaper"",
                    ""type"": ""Button"",
                    ""id"": ""fdeca27b-5f64-41fd-9ea8-8594c46251a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""348d3fb9-3d99-4703-8936-b76437471ad2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpRock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""660f795e-3298-47d2-8d0f-1c169cdbfb21"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpScissors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""426d7fa0-df59-4b11-897e-48ef674cd44c"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpPaper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37ff50fa-7391-4919-83e3-2067acdb7aa8"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownRock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a7ea608-af0a-48dd-a0cf-d3c60b3703bf"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownScissors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97f34af8-902a-4a46-a000-810b45ecbc05"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownPaper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0716f56e-1e7d-404d-b524-352a0b41ef3b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpRock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52a23c9f-924f-4aab-83b6-216635bdcea3"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpScissors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32a950f1-8fad-40c2-a447-0f7f15284154"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpPaper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a7a08bf-902e-4abb-9435-adaaca050bb1"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownRock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cae54a2-7f7f-4dab-8a73-f52af1b44d08"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownScissors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6408fea-3069-4134-ad55-5b5bc0f71348"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownPaper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Janken
        m_Janken = asset.FindActionMap("Janken", throwIfNotFound: true);
        m_Janken_LeftUpRock = m_Janken.FindAction("LeftUpRock", throwIfNotFound: true);
        m_Janken_LeftUpScissors = m_Janken.FindAction("LeftUpScissors", throwIfNotFound: true);
        m_Janken_LeftUpPaper = m_Janken.FindAction("LeftUpPaper", throwIfNotFound: true);
        m_Janken_LeftDownRock = m_Janken.FindAction("LeftDownRock", throwIfNotFound: true);
        m_Janken_LeftDownScissors = m_Janken.FindAction("LeftDownScissors", throwIfNotFound: true);
        m_Janken_LeftDownPaper = m_Janken.FindAction("LeftDownPaper", throwIfNotFound: true);
        m_Janken_RightUpRock = m_Janken.FindAction("RightUpRock", throwIfNotFound: true);
        m_Janken_RightUpScissors = m_Janken.FindAction("RightUpScissors", throwIfNotFound: true);
        m_Janken_RightUpPaper = m_Janken.FindAction("RightUpPaper", throwIfNotFound: true);
        m_Janken_RightDownRock = m_Janken.FindAction("RightDownRock", throwIfNotFound: true);
        m_Janken_RightDownScissors = m_Janken.FindAction("RightDownScissors", throwIfNotFound: true);
        m_Janken_RightDownPaper = m_Janken.FindAction("RightDownPaper", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_Janken.enabled, "This will cause a leak and performance issues, GameInputActions.Janken.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Janken
    private readonly InputActionMap m_Janken;
    private List<IJankenActions> m_JankenActionsCallbackInterfaces = new List<IJankenActions>();
    private readonly InputAction m_Janken_LeftUpRock;
    private readonly InputAction m_Janken_LeftUpScissors;
    private readonly InputAction m_Janken_LeftUpPaper;
    private readonly InputAction m_Janken_LeftDownRock;
    private readonly InputAction m_Janken_LeftDownScissors;
    private readonly InputAction m_Janken_LeftDownPaper;
    private readonly InputAction m_Janken_RightUpRock;
    private readonly InputAction m_Janken_RightUpScissors;
    private readonly InputAction m_Janken_RightUpPaper;
    private readonly InputAction m_Janken_RightDownRock;
    private readonly InputAction m_Janken_RightDownScissors;
    private readonly InputAction m_Janken_RightDownPaper;
    /// <summary>
    /// Provides access to input actions defined in input action map "Janken".
    /// </summary>
    public struct JankenActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public JankenActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Janken/LeftUpRock".
        /// </summary>
        public InputAction @LeftUpRock => m_Wrapper.m_Janken_LeftUpRock;
        /// <summary>
        /// Provides access to the underlying input action "Janken/LeftUpScissors".
        /// </summary>
        public InputAction @LeftUpScissors => m_Wrapper.m_Janken_LeftUpScissors;
        /// <summary>
        /// Provides access to the underlying input action "Janken/LeftUpPaper".
        /// </summary>
        public InputAction @LeftUpPaper => m_Wrapper.m_Janken_LeftUpPaper;
        /// <summary>
        /// Provides access to the underlying input action "Janken/LeftDownRock".
        /// </summary>
        public InputAction @LeftDownRock => m_Wrapper.m_Janken_LeftDownRock;
        /// <summary>
        /// Provides access to the underlying input action "Janken/LeftDownScissors".
        /// </summary>
        public InputAction @LeftDownScissors => m_Wrapper.m_Janken_LeftDownScissors;
        /// <summary>
        /// Provides access to the underlying input action "Janken/LeftDownPaper".
        /// </summary>
        public InputAction @LeftDownPaper => m_Wrapper.m_Janken_LeftDownPaper;
        /// <summary>
        /// Provides access to the underlying input action "Janken/RightUpRock".
        /// </summary>
        public InputAction @RightUpRock => m_Wrapper.m_Janken_RightUpRock;
        /// <summary>
        /// Provides access to the underlying input action "Janken/RightUpScissors".
        /// </summary>
        public InputAction @RightUpScissors => m_Wrapper.m_Janken_RightUpScissors;
        /// <summary>
        /// Provides access to the underlying input action "Janken/RightUpPaper".
        /// </summary>
        public InputAction @RightUpPaper => m_Wrapper.m_Janken_RightUpPaper;
        /// <summary>
        /// Provides access to the underlying input action "Janken/RightDownRock".
        /// </summary>
        public InputAction @RightDownRock => m_Wrapper.m_Janken_RightDownRock;
        /// <summary>
        /// Provides access to the underlying input action "Janken/RightDownScissors".
        /// </summary>
        public InputAction @RightDownScissors => m_Wrapper.m_Janken_RightDownScissors;
        /// <summary>
        /// Provides access to the underlying input action "Janken/RightDownPaper".
        /// </summary>
        public InputAction @RightDownPaper => m_Wrapper.m_Janken_RightDownPaper;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Janken; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="JankenActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(JankenActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="JankenActions" />
        public void AddCallbacks(IJankenActions instance)
        {
            if (instance == null || m_Wrapper.m_JankenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JankenActionsCallbackInterfaces.Add(instance);
            @LeftUpRock.started += instance.OnLeftUpRock;
            @LeftUpRock.performed += instance.OnLeftUpRock;
            @LeftUpRock.canceled += instance.OnLeftUpRock;
            @LeftUpScissors.started += instance.OnLeftUpScissors;
            @LeftUpScissors.performed += instance.OnLeftUpScissors;
            @LeftUpScissors.canceled += instance.OnLeftUpScissors;
            @LeftUpPaper.started += instance.OnLeftUpPaper;
            @LeftUpPaper.performed += instance.OnLeftUpPaper;
            @LeftUpPaper.canceled += instance.OnLeftUpPaper;
            @LeftDownRock.started += instance.OnLeftDownRock;
            @LeftDownRock.performed += instance.OnLeftDownRock;
            @LeftDownRock.canceled += instance.OnLeftDownRock;
            @LeftDownScissors.started += instance.OnLeftDownScissors;
            @LeftDownScissors.performed += instance.OnLeftDownScissors;
            @LeftDownScissors.canceled += instance.OnLeftDownScissors;
            @LeftDownPaper.started += instance.OnLeftDownPaper;
            @LeftDownPaper.performed += instance.OnLeftDownPaper;
            @LeftDownPaper.canceled += instance.OnLeftDownPaper;
            @RightUpRock.started += instance.OnRightUpRock;
            @RightUpRock.performed += instance.OnRightUpRock;
            @RightUpRock.canceled += instance.OnRightUpRock;
            @RightUpScissors.started += instance.OnRightUpScissors;
            @RightUpScissors.performed += instance.OnRightUpScissors;
            @RightUpScissors.canceled += instance.OnRightUpScissors;
            @RightUpPaper.started += instance.OnRightUpPaper;
            @RightUpPaper.performed += instance.OnRightUpPaper;
            @RightUpPaper.canceled += instance.OnRightUpPaper;
            @RightDownRock.started += instance.OnRightDownRock;
            @RightDownRock.performed += instance.OnRightDownRock;
            @RightDownRock.canceled += instance.OnRightDownRock;
            @RightDownScissors.started += instance.OnRightDownScissors;
            @RightDownScissors.performed += instance.OnRightDownScissors;
            @RightDownScissors.canceled += instance.OnRightDownScissors;
            @RightDownPaper.started += instance.OnRightDownPaper;
            @RightDownPaper.performed += instance.OnRightDownPaper;
            @RightDownPaper.canceled += instance.OnRightDownPaper;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="JankenActions" />
        private void UnregisterCallbacks(IJankenActions instance)
        {
            @LeftUpRock.started -= instance.OnLeftUpRock;
            @LeftUpRock.performed -= instance.OnLeftUpRock;
            @LeftUpRock.canceled -= instance.OnLeftUpRock;
            @LeftUpScissors.started -= instance.OnLeftUpScissors;
            @LeftUpScissors.performed -= instance.OnLeftUpScissors;
            @LeftUpScissors.canceled -= instance.OnLeftUpScissors;
            @LeftUpPaper.started -= instance.OnLeftUpPaper;
            @LeftUpPaper.performed -= instance.OnLeftUpPaper;
            @LeftUpPaper.canceled -= instance.OnLeftUpPaper;
            @LeftDownRock.started -= instance.OnLeftDownRock;
            @LeftDownRock.performed -= instance.OnLeftDownRock;
            @LeftDownRock.canceled -= instance.OnLeftDownRock;
            @LeftDownScissors.started -= instance.OnLeftDownScissors;
            @LeftDownScissors.performed -= instance.OnLeftDownScissors;
            @LeftDownScissors.canceled -= instance.OnLeftDownScissors;
            @LeftDownPaper.started -= instance.OnLeftDownPaper;
            @LeftDownPaper.performed -= instance.OnLeftDownPaper;
            @LeftDownPaper.canceled -= instance.OnLeftDownPaper;
            @RightUpRock.started -= instance.OnRightUpRock;
            @RightUpRock.performed -= instance.OnRightUpRock;
            @RightUpRock.canceled -= instance.OnRightUpRock;
            @RightUpScissors.started -= instance.OnRightUpScissors;
            @RightUpScissors.performed -= instance.OnRightUpScissors;
            @RightUpScissors.canceled -= instance.OnRightUpScissors;
            @RightUpPaper.started -= instance.OnRightUpPaper;
            @RightUpPaper.performed -= instance.OnRightUpPaper;
            @RightUpPaper.canceled -= instance.OnRightUpPaper;
            @RightDownRock.started -= instance.OnRightDownRock;
            @RightDownRock.performed -= instance.OnRightDownRock;
            @RightDownRock.canceled -= instance.OnRightDownRock;
            @RightDownScissors.started -= instance.OnRightDownScissors;
            @RightDownScissors.performed -= instance.OnRightDownScissors;
            @RightDownScissors.canceled -= instance.OnRightDownScissors;
            @RightDownPaper.started -= instance.OnRightDownPaper;
            @RightDownPaper.performed -= instance.OnRightDownPaper;
            @RightDownPaper.canceled -= instance.OnRightDownPaper;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="JankenActions.UnregisterCallbacks(IJankenActions)" />.
        /// </summary>
        /// <seealso cref="JankenActions.UnregisterCallbacks(IJankenActions)" />
        public void RemoveCallbacks(IJankenActions instance)
        {
            if (m_Wrapper.m_JankenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="JankenActions.AddCallbacks(IJankenActions)" />
        /// <seealso cref="JankenActions.RemoveCallbacks(IJankenActions)" />
        /// <seealso cref="JankenActions.UnregisterCallbacks(IJankenActions)" />
        public void SetCallbacks(IJankenActions instance)
        {
            foreach (var item in m_Wrapper.m_JankenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JankenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="JankenActions" /> instance referencing this action map.
    /// </summary>
    public JankenActions @Janken => new JankenActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Janken" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="JankenActions.AddCallbacks(IJankenActions)" />
    /// <seealso cref="JankenActions.RemoveCallbacks(IJankenActions)" />
    public interface IJankenActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftUpRock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftUpRock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftUpScissors" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftUpScissors(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftUpPaper" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftUpPaper(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftDownRock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftDownRock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftDownScissors" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftDownScissors(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftDownPaper" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftDownPaper(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightUpRock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightUpRock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightUpScissors" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightUpScissors(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightUpPaper" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightUpPaper(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightDownRock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightDownRock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightDownScissors" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightDownScissors(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightDownPaper" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightDownPaper(InputAction.CallbackContext context);
    }
}
